admin_app/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'admin_app'

urlpatterns = [
    path('idn_domain_forms', views.idn_domain_forms, name="idn_domain_forms"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('email_compose', views.email_compose, name="email_compose"),
    path('sent_email_view', views.sent_email_view, name="sent_email_view"),
    path('sent_email_view_detail/<int:id>', views.sent_email_view_detail, name="sent_email_view_detail"),
    path('refresh_domain_parameters/<int:id>', views.refresh_domain_parameters, name="refresh_domain_parameters"),
    path('edit_idn_domain_forms/<int:id>', views.edit_idn_domain_forms, name="edit_idn_domain_forms"),
    path('show_logs',views.show_logs,name="show_logs"),
    path('clear_logs',views.clear_logs,name="clear_logs"),
    path('show_logs_last',views.show_logs_last,name="show_logs_last"),
    path('upload_excel',views.upload_excel,name="upload_excel"),
    path('dashboard2', views.dashboard2, name="dashboard2"),
    path('idn_domain_list',views.idn_domain_list, name='idn_domain_list'),
    path('english_domain_list',views.english_domain_list,name='english_domain_list'),
    path('update_all_domains',views.update_all_domains,name='update_all_domains'),
    path('tinymce/', include('tinymce.urls')),
    path('logout', views.logout_view, name='logout_view'),
]

bhashanet_v2/urls.py
from .url.tamil_urls import Translation_urlpatterns_tamil
from .url.telugu_urls import Translation_urlpatterns_telugu
from .url.kashmiri_urls import Translation_urlpatterns_kashmiri
from .url.maithili_urls import Translation_urlpatterns_maithili
from .url.sanskrit_urls import Translation_urlpatterns_sanskrit
from .url.santali_urls import Translation_urlpatterns_santali
from .url.sindhi_urls import Translation_urlpatterns_sindhi
from .url.urdu_urls import Translation_urlpatterns_urdu


sitemaps = {
    'bhashanet_static': StaticSitemap,
}

# -----ADDED BY SHWETA PATIL -------
urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    # path('rosetta/', include('rosetta.urls')),
    path('captcha_refresh/', core_views.captcha_refresh, name='captcha_refresh'),  # added by shivam sharma
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('submit_reply_to_answer/<slug:topic_slug>/<answer_id>', submit_reply_to_answer, name='submit_reply_to_answer'),
    path('submit_reply_to_answer_2/<slug:topic_slug>/<answer_id>/<reply_id>', submit_reply_to_answer_2, name='submit_reply_to_answer_2'),
    path('SopDownloadCounter/<int:id>', core_views.SopDownloadCounter,name='SopDownloadCounter'),
    path('update_json', core_views.update_json, name="update_json"),
    path('display_table2', core_views.display_table2, name="display_table2"),
    path('idn_rediness_dashboard', core_views.idn_rediness_dashboard, name="idn_rediness_dashboard"),  
    path('bhashanet_dashboard/', include('admin_app.urls')),   
]


Translation_urlpatterns = [
    path((''), core_views.landingfunction, name='home'),
    path('home', core_views.home, name='home'),
    path('privacypolicy', preprocesslangset(core_views.privacypolicy), name='privacypolicy'),
    path('termsandconditions', preprocesslangset(core_views.termsandconditions), name='termsandconditions'),
    path('uaindiaprogramme', preprocesslangset(core_views.uaindiaprogramme), name='uaindiaprogramme'),
    path('IDNCCTLD', preprocesslangset(core_views.IDNCCTLD), name='IDNCCTLD'),
    path('bestpractices', preprocesslangset(core_views.bestpractices), name='bestpractices'),
    path('EAI', preprocesslangset(core_views.EAI), name='EAI'),
    path('UA', preprocesslangset(core_views.UA), name='UA'),
    path('tools', preprocesslangset(core_views.tools), name='tools'),
    path('unicode_punycode_generator', preprocesslangset(core_views.unicode_punycode_generator), name='unicode_punycode_generator'),
    path('unicode_fonts', preprocesslangset(core_views.unicode_fonts), name='unicode_fonts'),
    path('transliteration', preprocesslangset(core_views.transliteration), name='transliteration'),
    path('script_detection', preprocesslangset(core_views.script_detection), name='script_detection'),
    path('domain_validator', preprocesslangset(core_views.domain_validator), name='domain_validator'),
    path('email_validator', preprocesslangset(core_views.email_validator), name='email_validator'),
    path('feedback', preprocesslangset(core_views.feedback), name='feedback'),
    path('becomeuaready', preprocesslangset(core_views.becomeuaready), name='becomeuaready'),
    path('FAQS', preprocesslangset(core_views.FAQs), name='FAQs'),
    path('documentPage', preprocesslangset(core_views.documentPage), name='documentPage'),
    path('documentData', preprocesslangset(core_views.documentData), name='documentData'),
    path('support', preprocesslangset(core_views.support), name='support'),
    path('testimonial', preprocesslangset(core_views.testimonial), name='testimonial'),
    path('search_results', preprocesslangset(core_views.search_results), name='search_results'),
    path('testimonials', preprocesslangset(core_views.testimonials), name='testimonials'),
    path('idn_websites/<str:id>', preprocesslangset(core_views.idn_websites), name='idn_websites'),
    path('event', preprocesslangset(core_views.event), name='event'),
    path('gallery', preprocesslangset(core_views.gallery), name='gallery'),
    path('language_detection', preprocesslangset(core_views.language_detection), name='language_detection'), # added by tanvi patil
    path('cdac_keyboard', preprocesslangset(core_views.cdac_keyboard), name='cdac_keyboard'), # added by tanvi patil
    path('sop_tech_page', preprocesslangset(core_views.SOPTechnalogyPage), name='sop_tech_page'), 
    path('sop_document_page', preprocesslangset(core_views.sop_document_page), name='sop_document_page'), 
    path('sop_document', preprocesslangset(core_views.sop_document), name='sop_document'), 
    path('tld_validator', preprocesslangset(core_views.tld_validator), name='tld_validator'),
    path('dashboard', preprocesslangset(core_views.dashboard), name='dashboard'),
    path('admindashboard', preprocesslangset(core_views.admindashboard), name='admindashboard'),
    path('blogs', preprocesslangset(core_views.blogs), name='blogs'),
    # path('cat_selected', core_views.cat_selected, name='cat_selected'),
    path('blogs/<str:id>', preprocesslangset(preprocesslangset(core_views.blogs)), name='blogs'),
    path('blog/<str:id>', preprocesslangset(core_views.blog), name='blog'),
    path('test_support', preprocesslangset(core_views.test_support), name='test_support'),
    path('idn_websites_request', preprocesslangset(core_views.idn_websites_request_AJAX), name='idn_websites_request_AJAX'),
    path('idn_websites_request1', preprocesslangset(core_views.idn_websites_request1), name='idn_websites_request1'),
    path('search_blog/<str:id>', preprocesslangset(user_views.search_blog), name='search_blog'),

    path('add_blog', preprocesslangset(user_views.add_blog), name='add_blog'),
    path('edit_blog/<str:id>', preprocesslangset(user_views.edit_blog), name='edit_blog'),
    path('delete_blog/<str:id>', preprocesslangset(user_views.delete_blog), name='delete_blog'),
    path('blog_datatable', preprocesslangset(user_views.admin_blog_datatable), name='admin_blog_datatable'),
    path('discussion_forum_topic_list', preprocesslangset(topic_list), name="topic_list"),
    path('discussion_forum_user_topic_list', preprocesslangset(user_topic_list), name="user_topic_list"),
    path('discussion_forum_add_topic', preprocesslangset(add_topic), name="add_topic"),
    path('discussion_forum_view_topic_discussion/<slug:topic_slug>', preprocesslangset(view_topic_discussion), name="view_topic_discussion"),
    path('submit_answer/<slug:topic_slug>', preprocesslangset(submit_answer), name='submit_answer'),
    path('upvote_answer', preprocesslangset(upvote_answer_view), name='upvote_answer_view'),
    #path('test_task', preprocesslangset(core_views.test_celery), name="test_task"),
    path('login',user_views.login_view, name="login_view"),
    path('login/<str:flag>', user_views.login_view, name="login_view"),
    path('register', preprocesslangset(user_views.register_view), name='register_view'),
    path('register/<str:flag>', preprocesslangset(user_views.register_view), name='register_view'),
    path('logout', preprocesslangset(user_views.logout_view), name='logout_view'),
    path('logout/<str:flag>', preprocesslangset(user_views.logout_view), name='logout_view'),
    path('change_password', preprocesslangset(user_views.change_password_view), name='change_password'),
    path('change_password/<str:flag>', preprocesslangset(user_views.change_password_view), name='change_password'),
    path('forgot_password', preprocesslangset(user_views.forgot_password_view), name='forgot_password'),
    path('forgot_password/<str:flag>', preprocesslangset(user_views.forgot_password_view), name='forgot_password'),
    path('password_creation/<uid>/<token>', preprocesslangset(user_views.password_creation_view), name='password_creation'),
    path('password_creation/<uid>/<token>/<str:flag>', preprocesslangset(user_views.password_creation_view), name='password_creation'),
    path('verify_user_otp/<str:email>', user_views.verify_user_otp, name='verify_user_otp'), ###Need to add in path.json and in all urls
    path('verify_user_otp/<str:email>/<str:flag>', user_views.verify_user_otp, name='verify_user_otp'), ###Need to add in path.json and in all urls
    path('user_profile', user_views.user_profile_view, name='user_profile'), ###Need to add in path.json and in all urls
    path('user_profile<str:flag>', user_views.user_profile_view, name='user_profile'), ###Need to add in path.json and in all urls
]

#### 475


# ----ADDED BY SHWETA PATIL ----
# urlpatterns = urlpatterns + Translation_urlpatterns + Translation_urlpatterns_hindi + Translation_urlpatterns_marathi + Translation_urlpatterns_kannada + Translation_urlpatterns_malayalam + Translation_urlpatterns_bengali + Translation_urlpatterns_manipuri + Translation_urlpatterns_gujarati + Translation_urlpatterns_punjabi + Translation_urlpatterns_telugu + Translation_urlpatterns_tamil + Translation_urlpatterns_assamese + Translation_urlpatterns_konkani + Translation_urlpatterns_nepali + Translation_urlpatterns_boro + Translation_urlpatterns_dogri + Translation_urlpatterns_oriya + Translation_urlpatterns_kashmiri +Translation_urlpatterns_maithili + Translation_urlpatterns_sanskrit + Translation_urlpatterns_santali + Translation_urlpatterns_sindhi + Translation_urlpatterns_urdu
urlpatterns = urlpatterns + Translation_urlpatterns


# ----ADDED BY SHWETA PATIL ----
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# ----ADDED BY SHWETA PATIL ----
handler404 = 'core_app.views.custom_page_not_found_view'
handler500 = 'core_app.views.custom_error_view'
handler403 = 'core_app.views.custom_permission_denied_view'

core_app/forms.py
from django import forms
from django.forms import ModelForm, Form
from .models import *
from ckeditor.widgets import CKEditorWidget
from ckeditor.fields import RichTextFormField
from .validate import *
from django.core import validators
from django.contrib.auth.forms import UserCreationForm


class Feedback_form(ModelForm):
    Feedback_FirstName = forms.CharField(label="Name", max_length=30, widget=forms.TextInput(
        attrs={'placeholder': 'Enter Your Name', 'id': 'Feedback_FirstName', 'class': 'form-control form-control-lg',
               'autocomplete': 'off'}))
    Feedback_Email = forms.CharField(label="Name", max_length=300, widget=forms.TextInput(
        attrs={'placeholder': 'Enter Your Email ID', 'id': 'Feedback_Email', 'class': 'form-control form-control-lg',
               'autocomplete': 'off'}))
    Feedback_Related_To = forms.ModelChoiceField(label='Select Category', required=True,
                                            help_text='Select Category',
                                            queryset=FeedbackCategory.objects.all(), widget=forms.Select(
            attrs={'style': 'border-color: grey ;margin-bottom:20px', 'placeholder': 'select',
                   'id': 'Feedback_Category', 'class': 'form-control form-control-lg', 'autocomplete': 'off'}), )
    Feedback_Message = forms.CharField(label=" Your Feedback", widget=forms.Textarea(
        attrs={'style': 'border-color: grey ;margin-bottom:20px', 'placeholder': 'Enter Your Feedback',
               'id': 'Feedback_Message', 'class': 'NALOC form-control form-control-lg', 'autocomplete': 'off'}))

    captcha_hidden = forms.CharField(widget=forms.HiddenInput(), required="False")
    captcha_input = forms.CharField(max_length=5, required=True, widget=forms.TextInput(
        attrs={'class': 'form-control', 'id': 'inputCaptcha', 'placeholder': 'Enter Captcha', 'name': 'captcha'}))

    class Meta:
        model = UserFeedbackData
        fields = [
            'Feedback_FirstName',
            'Feedback_Email',
            'Feedback_Related_To',
            'Feedback_Message'
        ]

    def clean(self):
        print("FORMS.PY FILE : CLEAN METHOD CALLING")
        # data is feteched using the super function of django
        super(Feedback_form, self).clean()
        validate_feedbackform(self)

# ---------------------------------------------------------------------------------------------------

class Domain_Syntax_Check_form(ModelForm):
    Domain_Name = forms.CharField(label="Domain", max_length=30, widget=forms.TextInput(
        attrs={'placeholder': 'Enter your domain', 'id': 'Domain', 'class': 'form-control form-control-lg',
               'autocomplete': 'off'}))

    class Meta:
        model = DomainSyntax
        fields = [
            'Domain_Name'
        ]

    def clean(self):
        print("FORMS.PY FILE : CLEAN METHOD CALLING")
        # data is feteched using the super function of django
        super(Domain_Syntax_Check_form, self).clean()
        validate_domain(self)

# ---------------------------------------------------------------------------------------------------

class Email_Syntax_Check_form(ModelForm):
    Email_Address = forms.CharField(label="Email", max_length=30, widget=forms.TextInput(
        attrs={'placeholder': 'Enter your Email', 'id': 'email', 'class': 'form-control form-control-lg',
               'autocomplete': 'off'}))

    class Meta:
        model = EmailSyntax
        fields = [
            'Email_Address'
        ]

    def clean(self):
        print("FORMS.PY FILE : CLEAN METHOD CALLING")
        # data is feteched using the super function of django
        super(Email_Syntax_Check_form, self).clean()
        validate_email(self)

# ---------------------------------------------------------------------------------------------------

class IDN_Ready_Websites(Form):
    select_category = forms.ModelMultipleChoiceField(queryset=IDNReadyWebsitesCategory.objects.all(), widget=forms.CheckboxSelectMultiple)
    select_language = forms.ModelMultipleChoiceField(queryset=IDNReadyWebsitesLanguages.objects.all(), widget=forms.CheckboxSelectMultiple)

# ---------------------------------------------------------------------------------------------------

class IDNRequestForUserWebsitesForm(ModelForm):
    IDN_Email = forms.CharField(max_length=500, required=True, 
                                widget=forms.TextInput(attrs={"class" : "form-control", "placeholder" : "Enter Email Address"}))
    IDN_Category = forms.ModelChoiceField(queryset=IDNRequestForUserWebsitesCategories.objects.filter(website_status="Active"), required=True, empty_label="Please Select",
                                     widget=forms.Select(attrs={"class" : "form-control", "placeholder" : "Domain Name (English)"}))
    IDN_English_Domain = forms.CharField(max_length=600, required=True, 
                                         widget=forms.TextInput(attrs={"class" : "form-control", "placeholder" : "Enter Domain Name (English)"}))
    
    
    captcha_hidden = forms.CharField(widget=forms.HiddenInput(), required="False")
    captcha_input = forms.CharField(max_length=5, required=True, widget=forms.TextInput(
        attrs={'class': 'form-control', 'id': 'inputCaptcha', 'placeholder': 'Enter Captcha', 'name': 'captcha'}))
    
    class Meta:
        model = IDNRequestForUserWebsites
        fields = [ "IDN_Email", "IDN_Category", "IDN_English_Domain" ]

   
    def clean(self):
        print("FORMS.PY FILE : CLEAN METHOD CALLING")
        super(IDNRequestForUserWebsitesForm, self).clean()
        validate_IDNRequestForUserWebsitesForm(self)

admin_app/templates/admin_app/AccountManagement/change_password.html
{% extends base_template %}
{% load static %} 

{% block change_password %}

<div class="card-box ua-card-header--bg-blk">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-12">
        <div class="ua-small-info-box">
          <div class="horizontal-rule">
            <h1 class="h2 heading4">Change Password</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<section>
  <div class="container mt-2">
    <div class="row">
      <div class="col-lg-12">
        <div class="breadcrumb-bar">
          <div class="container">
            <div class="row">
              <div class="col-md-12 col-12">
                <div class="breadcrumb-list">
                  <nav aria-label="breadcrumb" class="page-breadcrumb">
                    <ol class="breadcrumb">
                      <li class="breadcrumb-item">
                        <a href="{% url 'home' %}">Home</a>
                      </li>
                      <li class="breadcrumb-item">Change Password</li>
                    </ol>
                  </nav>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="page-content ua-sec" id="main-content">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-8 mx-auto">
        <div>
          {% if messages %} 
          {% for message in messages %}
          <div class="alert alert-{{message.extra_tags}} alert-dismissible" role="alert">
            <strong> {% if message.tags %}{{message}}{% endif %}</strong>
          </div>
          {% endfor %} {% endif %}
        </div>

        <div style="color: red">
          {% if form.non_field_errors %} 
          {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
          </div>
          {% endfor %} {% endif %}
        </div>
        <div class="support-wrap shadow-sm bg-white px-3 py-5">
          <form method="POST" novalidate>
            {% csrf_token %}
            <div class="form-group">
              <label for="Feedback_Email" class="form-label">Old Password</label>
              {{form.old_password}}
            </div>
            <div class="form-group">
              <label for="Feedback_Email" class="form-label">New Password<i class="fa fa-question-circle fa-sm" aria-hidden="true" title="Password must contain minimum 8 characters with minimum 1 uppercase character, 1 lowercase character, 1 number and 1 special symbol"></i></label>
              {{form.new_password}}
            </div>
            <div class="form-group">
              <label for="Feedback_Email" class="form-label">Confirm New Password</label>
              {{form.confirm_password}}
            </div>

            <div class=" mt-3">
              <button class="btn login-form__btn submit w-100" style="color:white;">Change Password</button>
            </div>
          </form>
        </div>
  </div>
</div>

</section>

{% endblock %}

admin_app/templates/admin_app/AccountManagement/forgot_password.html
{% extends base_template %} {% load static %}

{% block forgot_password %}

<div class="card-box ua-card-header--bg-blk">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-12">
        <div class="ua-small-info-box">
          <div class="horizontal-rule">
            <h1 class="h2 heading4">Forgot Password</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<section>
  <div class="container mt-2">
    <div class="row">
      <div class="col-lg-12">
        <div class="breadcrumb-bar">
          <div class="container">
            <div class="row">
              <div class="col-md-12 col-12">
                <div class="breadcrumb-list">
                  <nav aria-label="breadcrumb" class="page-breadcrumb">
                    <ol class="breadcrumb">
                      <li class="breadcrumb-item">
                        <a href="{% url 'home' %}">Home</a>
                      </li>
                      <li class="breadcrumb-item">Forgot Password</li>
                    </ol>
                  </nav>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="page-content ua-sec" id="main-content">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-8 mx-auto">
        <div>
          {% if messages %} 
          {% for message in messages %}
          <div class="alert alert-{{message.extra_tags}} alert-dismissible" role="alert">
            <strong> {% if message.tags %}{{message}}{% endif %}</strong>
          </div>
          {% endfor %} {% endif %}
        </div>

        <div style="color: red">
          {% if form.non_field_errors %} 
          {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
          </div>
          {% endfor %} {% endif %}
        </div>
        <div class="support-wrap shadow-sm bg-white px-3 py-5">
          <form method="POST" novalidate>
            {% csrf_token %}
            <div class="form-group">
              <label for="Feedback_Email" class="form-label">Email Address</label>
              {{form.email}}
            </div>

              <!-- Captcha input -->
              <div class="form-outline mb-4 mt-2">
                <div class="row">
                  <div class="col-sm-12 col-lg-5">
                    <label class="mb-1 fs-5 fw-semibold px-1" for="inputCaptcha">Captcha</label>
                    {{form.captcha_input}}
                    {{form.captcha_hidden}}
                  </div>
                  <div class="col-sm-12 col-lg-5 mt-2">
                    <img class="img-fluid" src='/media/captcha_images/CAPTCHA.png' alt="Captcha" id="captcha-img" width="220">
                    <i class="fa fa-refresh fa-lg m-2" aria-hidden="true" id="refresh_button"></i>
                    <!-- <i class="fa-solid fa-volume-high" name="speaker" onclick="readaudio()"></i> -->
                  </div>
                </div>
              </div>

            <div class=" mt-3">
              <button class="btn btn-primary btn-lg">Submit</button>
            </div>
          </form>
          <div class="text-center text-lg-start mt-2 pt-2">
            <p class="small fw-bold mt-1 pt-1 mb-0 fs-6">
              Does not have an account ?
              <a href="{% url 'register_view' 'for_user_register' %}" class="link-danger">Register</a>
            </p>
          </div>
        </div>
  </div>
</div>

</section>


<script>
  $('#captcha-img').attr('src', '/media/captcha_images/CAPTCHA.png' + "?t="+new Date().getTime())

   $('#refresh_button').click(function () {
      console.log("refresh button clicked")
      $.ajax({
            type: "GET",
            url: '/captcha_refresh/'
      }).done(function (result){
            let image = result.captcha_url
            $('#captcha-img').attr('src', '/media'+image+"?t="+new Date().getTime())
            //$('#captcha-img').attr('src', '/static'+image)
            $('#id_captcha_hidden').val(result.captcha_value)
      })
      return false;
   })
</script>

{% endblock %}

admin_app/templates/admin_app/AccountManagement/user_login.html
{% extends base_template %}
{% load static %}
 
{% block user_login %}

<div class="card-box ua-card-header--bg-blk">
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-12">
        <div class="ua-small-info-box">
          <div class="horizontal-rule">
            <h1 class="h2 heading4">Login</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<section>
  <div class="container mt-2">
    <div class="row">
      <div class="col-lg-12">
        <div class="breadcrumb-bar">
          <div class="container">
            <div class="row">
              <div class="col-md-12 col-12">
                <div class="breadcrumb-list">
                  {% comment %} <nav aria-label="breadcrumb" class="page-breadcrumb">
                    <ol class="breadcrumb">
                      <li class="breadcrumb-item">
                        <a href="{% url 'home' %}">Home</a>
                      </li>
                      <li class="breadcrumb-item">Login</li>
                    </ol>
                  </nav> {% endcomment %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="page-content ua-sec" id="main-content">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-8 mx-auto">
        <div>
          {% if messages %} 
          {% for message in messages %}
          <div class="alert alert-{{message.extra_tags}} alert-dismissible" role="alert">
            <strong> {% if message.tags %}{{message}}{% endif %}</strong>
          </div>
          {% endfor %} {% endif %}
        </div>

        <div style="color: red">
          {% if form.non_field_errors %} 
          {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
          </div>
          {% endfor %} {% endif %}
        </div>
        <div class="support-wrap shadow-sm bg-white px-3 py-5">
          <form method="POST" novalidate>
            {% csrf_token %}
            <div class="form-group">
              <label for="Feedback_Email" class="form-label">Email</label>
              {{form.username}}
            </div>
            <div class="form-group">
              <label for="Feedback_Email" class="form-label">Password</label>
              {{form.password}}
            </div>

              <!-- Captcha input -->
              <div class="form-outline mb-4 mt-2">
                <div class="row">
                  <div class="col-sm-12 col-lg-5">
                    <label class="mb-1 fs-5 fw-semibold px-1" for="inputCaptcha">Captcha</label>
                    {{form.captcha_input}}
                    {{form.captcha_hidden}}
                  </div>
                  <div class="col-sm-12 col-lg-5 mt-2">
                    <img class="img-fluid" src='/media/captcha_images/CAPTCHA.png' alt="Captcha" id="captcha-img" width="220">
                    <i class="fa fa-refresh fa-lg m-2" aria-hidden="true" id="refresh_button"></i>
                    <!-- <i class="fa-solid fa-volume-high" name="speaker" onclick="readaudio()"></i> -->
                  </div>
                </div>
              </div>

            <div class=" mt-3">
              <button class="btn login-form__btn submit w-100" style="color:white;">Login</button>
            </div>
          </form>
          {% if base_template == "core_app/base.html" %}
          <div class="text-center text-lg-start mt-2 pt-2">
            <p class="small fw-bold mt-1 pt-1 mb-0 fs-6">
              Does not have an account ?
              <a href="{% url 'register_view' 'for_user_register'  %}" class="link-danger">Register</a>
            </p>
          </div>
         <div class="d-flex justify-content-between fs-6 align-items-center">
            <a href="{% url 'forgot_password' 'for_user_forgot_password' %}" class="link-danger fw-bold">Forgot password?</a>
          </div>
          {% endif %}

        </div>
  </div>
</div>

</section>


<script>
  $('#captcha-img').attr('src', '/media/captcha_images/CAPTCHA.png' + "?t="+new Date().getTime())

   $('#refresh_button').click(function () {
      console.log("refresh button clicked")
      $.ajax({
            type: "GET",
            url: '/captcha_refresh/'
      }).done(function (result){
            let image = result.captcha_url
            $('#captcha-img').attr('src', '/media'+image+"?t="+new Date().getTime())
            //$('#captcha-img').attr('src', '/static'+image)
            $('#id_captcha_hidden').val(result.captcha_value)
      })
      return false;
   })
</script>

{% endblock %}