admin_app/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'admin_app'

urlpatterns = [
    path('idn_domain_forms', views.idn_domain_forms, name="idn_domain_forms"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('email_compose', views.email_compose, name="email_compose"),
    path('sent_email_view', views.sent_email_view, name="sent_email_view"),
    path('sent_email_view_detail/<int:id>', views.sent_email_view_detail, name="sent_email_view_detail"),
    path('refresh_domain_parameters/<int:id>', views.refresh_domain_parameters, name="refresh_domain_parameters"),
    path('edit_idn_domain_forms/<int:id>', views.edit_idn_domain_forms, name="edit_idn_domain_forms"),
    path('show_logs',views.show_logs,name="show_logs"),
    path('clear_logs',views.clear_logs,name="clear_logs"),
    path('show_logs_last',views.show_logs_last,name="show_logs_last"),
    path('upload_excel',views.upload_excel,name="upload_excel"),
    path('dashboard2', views.dashboard2, name="dashboard2"),
    path('idn_domain_list',views.idn_domain_list, name='idn_domain_list'),
    path('english_domain_list',views.english_domain_list,name='english_domain_list'),
    path('update_all_domains',views.update_all_domains,name='update_all_domains'),
    path('tinymce/', include('tinymce.urls')),
    path('logout', views.logout_view, name='logout_view'),
]

bhashanet_v2/urls.py
# ----ADDED BY SHWETA PATIL ----
from django.contrib import admin
from django.urls import path, include, re_path as url
from django.conf import settings
from django.conf.urls.static import static
from core_app import views as core_views
from admin_app import views as user_views
from django.views.static import serve
from discussion_forum_app.views import *
from django.contrib.sitemaps.views import sitemap
from core_app.sitemap import StaticSitemap
from core_app.decorator import preprocesslangset

# ----ADDED BY SHWETA PATIL ----
from .url.assamese_urls import Translation_urlpatterns_assamese
from .url.bengali_urls import Translation_urlpatterns_bengali
from .url.boro_urls import Translation_urlpatterns_boro
from .url.dogri_urls import Translation_urlpatterns_dogri
from .url.gujarati_urls import Translation_urlpatterns_gujarati
from .url.hindi_urls import Translation_urlpatterns_hindi
from .url.kannada_urls import Translation_urlpatterns_kannada
from .url.konkani_urls import Translation_urlpatterns_konkani
from .url.malayalam_urls import Translation_urlpatterns_malayalam
from .url.manipuri_urls import Translation_urlpatterns_manipuri
from .url.marathi_urls import Translation_urlpatterns_marathi
from .url.nepali_urls import Translation_urlpatterns_nepali
from .url.oriya_urls import Translation_urlpatterns_oriya
from .url.punjabi_urls import Translation_urlpatterns_punjabi
from .url.tamil_urls import Translation_urlpatterns_tamil
from .url.telugu_urls import Translation_urlpatterns_telugu
from .url.kashmiri_urls import Translation_urlpatterns_kashmiri
from .url.maithili_urls import Translation_urlpatterns_maithili
from .url.sanskrit_urls import Translation_urlpatterns_sanskrit
from .url.santali_urls import Translation_urlpatterns_santali
from .url.sindhi_urls import Translation_urlpatterns_sindhi
from .url.urdu_urls import Translation_urlpatterns_urdu


sitemaps = {
    'bhashanet_static': StaticSitemap,
}

# -----ADDED BY SHWETA PATIL -------
urlpatterns = [
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    # path('rosetta/', include('rosetta.urls')),
    path('captcha_refresh/', core_views.captcha_refresh, name='captcha_refresh'),  # added by shivam sharma
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('submit_reply_to_answer/<slug:topic_slug>/<answer_id>', submit_reply_to_answer, name='submit_reply_to_answer'),
    path('submit_reply_to_answer_2/<slug:topic_slug>/<answer_id>/<reply_id>', submit_reply_to_answer_2, name='submit_reply_to_answer_2'),
    path('SopDownloadCounter/<int:id>', core_views.SopDownloadCounter,name='SopDownloadCounter'),
    path('update_json', core_views.update_json, name="update_json"),
    path('display_table2', core_views.display_table2, name="display_table2"),
    path('idn_rediness_dashboard', core_views.idn_rediness_dashboard, name="idn_rediness_dashboard"),  
    path('bhashanet_dashboard/', include('admin_app.urls')),   
]


Translation_urlpatterns = [
    path((''), core_views.landingfunction, name='home'),
    path('home', core_views.home, name='home'),
    path('privacypolicy', preprocesslangset(core_views.privacypolicy), name='privacypolicy'),
    path('termsandconditions', preprocesslangset(core_views.termsandconditions), name='termsandconditions'),
    path('uaindiaprogramme', preprocesslangset(core_views.uaindiaprogramme), name='uaindiaprogramme'),
    path('IDNCCTLD', preprocesslangset(core_views.IDNCCTLD), name='IDNCCTLD'),
    path('bestpractices', preprocesslangset(core_views.bestpractices), name='bestpractices'),
    path('EAI', preprocesslangset(core_views.EAI), name='EAI'),
    path('UA', preprocesslangset(core_views.UA), name='UA'),
    path('tools', preprocesslangset(core_views.tools), name='tools'),
    path('unicode_punycode_generator', preprocesslangset(core_views.unicode_punycode_generator), name='unicode_punycode_generator'),
    path('unicode_fonts', preprocesslangset(core_views.unicode_fonts), name='unicode_fonts'),
    path('transliteration', preprocesslangset(core_views.transliteration), name='transliteration'),
    path('script_detection', preprocesslangset(core_views.script_detection), name='script_detection'),
    path('domain_validator', preprocesslangset(core_views.domain_validator), name='domain_validator'),
    path('email_validator', preprocesslangset(core_views.email_validator), name='email_validator'),
    path('feedback', preprocesslangset(core_views.feedback), name='feedback'),
    path('becomeuaready', preprocesslangset(core_views.becomeuaready), name='becomeuaready'),
    path('FAQS', preprocesslangset(core_views.FAQs), name='FAQs'),
    path('documentPage', preprocesslangset(core_views.documentPage), name='documentPage'),
    path('documentData', preprocesslangset(core_views.documentData), name='documentData'),
    path('support', preprocesslangset(core_views.support), name='support'),
    path('testimonial', preprocesslangset(core_views.testimonial), name='testimonial'),
    path('search_results', preprocesslangset(core_views.search_results), name='search_results'),
    path('testimonials', preprocesslangset(core_views.testimonials), name='testimonials'),
    path('idn_websites/<str:id>', preprocesslangset(core_views.idn_websites), name='idn_websites'),
    path('event', preprocesslangset(core_views.event), name='event'),
    path('gallery', preprocesslangset(core_views.gallery), name='gallery'),
    path('language_detection', preprocesslangset(core_views.language_detection), name='language_detection'), # added by tanvi patil
    path('cdac_keyboard', preprocesslangset(core_views.cdac_keyboard), name='cdac_keyboard'), # added by tanvi patil
    path('sop_tech_page', preprocesslangset(core_views.SOPTechnalogyPage), name='sop_tech_page'), 
    path('sop_document_page', preprocesslangset(core_views.sop_document_page), name='sop_document_page'), 
    path('sop_document', preprocesslangset(core_views.sop_document), name='sop_document'), 
    path('tld_validator', preprocesslangset(core_views.tld_validator), name='tld_validator'),
    path('dashboard', preprocesslangset(core_views.dashboard), name='dashboard'),
    path('admindashboard', preprocesslangset(core_views.admindashboard), name='admindashboard'),
    path('blogs', preprocesslangset(core_views.blogs), name='blogs'),
    # path('cat_selected', core_views.cat_selected, name='cat_selected'),
    path('blogs/<str:id>', preprocesslangset(preprocesslangset(core_views.blogs)), name='blogs'),
    path('blog/<str:id>', preprocesslangset(core_views.blog), name='blog'),
    path('test_support', preprocesslangset(core_views.test_support), name='test_support'),
    path('idn_websites_request', preprocesslangset(core_views.idn_websites_request_AJAX), name='idn_websites_request_AJAX'),
    path('idn_websites_request1', preprocesslangset(core_views.idn_websites_request1), name='idn_websites_request1'),
    path('search_blog/<str:id>', preprocesslangset(user_views.search_blog), name='search_blog'),

    path('add_blog', preprocesslangset(user_views.add_blog), name='add_blog'),
    path('edit_blog/<str:id>', preprocesslangset(user_views.edit_blog), name='edit_blog'),
    path('delete_blog/<str:id>', preprocesslangset(user_views.delete_blog), name='delete_blog'),
    path('blog_datatable', preprocesslangset(user_views.admin_blog_datatable), name='admin_blog_datatable'),
    path('discussion_forum_topic_list', preprocesslangset(topic_list), name="topic_list"),
    path('discussion_forum_user_topic_list', preprocesslangset(user_topic_list), name="user_topic_list"),
    path('discussion_forum_add_topic', preprocesslangset(add_topic), name="add_topic"),
    path('discussion_forum_view_topic_discussion/<slug:topic_slug>', preprocesslangset(view_topic_discussion), name="view_topic_discussion"),
    path('submit_answer/<slug:topic_slug>', preprocesslangset(submit_answer), name='submit_answer'),
    path('upvote_answer', preprocesslangset(upvote_answer_view), name='upvote_answer_view'),
    #path('test_task', preprocesslangset(core_views.test_celery), name="test_task"),
    path('login',user_views.login_view, name="login_view"),
    path('login/<str:flag>', user_views.login_view, name="login_view"),
    path('register', preprocesslangset(user_views.register_view), name='register_view'),
    path('register/<str:flag>', preprocesslangset(user_views.register_view), name='register_view'),
    path('logout', preprocesslangset(user_views.logout_view), name='logout_view'),
    path('logout/<str:flag>', preprocesslangset(user_views.logout_view), name='logout_view'),
    path('change_password', preprocesslangset(user_views.change_password_view), name='change_password'),
    path('change_password/<str:flag>', preprocesslangset(user_views.change_password_view), name='change_password'),
    path('forgot_password', preprocesslangset(user_views.forgot_password_view), name='forgot_password'),
    path('forgot_password/<str:flag>', preprocesslangset(user_views.forgot_password_view), name='forgot_password'),
    path('password_creation/<uid>/<token>', preprocesslangset(user_views.password_creation_view), name='password_creation'),
    path('password_creation/<uid>/<token>/<str:flag>', preprocesslangset(user_views.password_creation_view), name='password_creation'),
    path('verify_user_otp/<str:email>', user_views.verify_user_otp, name='verify_user_otp'), ###Need to add in path.json and in all urls
    path('verify_user_otp/<str:email>/<str:flag>', user_views.verify_user_otp, name='verify_user_otp'), ###Need to add in path.json and in all urls
    path('user_profile', user_views.user_profile_view, name='user_profile'), ###Need to add in path.json and in all urls

admin_app/templates/admin_app/admin_blog_datatable.html
{% extends 'admin_app/base.html' %}
{% load static %}

{% block blog_datatable %}

<div class="card-box ua-card-header--bg-blk">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-12">
                <div class="ua-small-info-box">
                    <div class="horizontal-rule">
                        <h1 class="h2 heading4">Blog List Table</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="breadcrumb-bar">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-12">
                <div class="breadcrumb-list">
                    {% comment %} <nav aria-label="breadcrumb" class="page-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
                            <li class="breadcrumb-item"><a href="{% url 'blogs' %}">Blogs</a></li>
                            <li class="breadcrumb-item">Blog List Table</li>
                        </ol>
                    </nav> {% endcomment %}
                </div>
            </div>
        </div>
    </div>
</div>
<section class="page-content" id="main-content">
    <div class="container-fluid h-custom">
    <div class="row mb-4">
        <div class="col-6">
          <!-- <h5 class="text-start mb-4">
            <a class="btn btn-primary rounded-3" href="{% url 'blogs' %}">Blog List</a>
          </h5> -->
        </div>
        {% comment %} <div class="col-6">
          <h5 class="text-end mb-4">
            <a class="btn btn-primary rounded-3" href="{% url 'add_blog' %}">Add New Blog</a>
          </h5>
        </div> {% endcomment %}
      </div>
   

    <div style="color:red">{% if messages %}
        {% for message in messages %}
        <small {% if message.tags %} class="{{message.tags}}">{{message}}{% endif %}</small>
        {% endfor %}
        {% endif %}
    </div>
    <div class="row d-flex justify-content-center align-items-center">
        <table class="table table-striped " id="mytable" style="width:100%;">
            <thead class="custom-datatable-thead">
            <tr>
                <th>S.No.</th>
                <th>Blog Title</th>
                <th>Category Type</th>
                <th>Creation Date</th>
                <th>Last Updated Date</th>
                <th>Author</th>
                <th>Publish Status</th>
                {% comment %} <th>View Details</th> {% endcomment %}
                <th>Edit</th>
                {% comment %} <th>Delete</th> {% endcomment %}

            </tr>
            </thead>
            <tbody>
            {% for data in blog_data %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{data.Blog_Title}}</td>
                <td>{{data.Blog_CategoryType}}</td>
                <td>{{data.Blog_CreationDate}}</td>
                <td>{{data.Blog_LastUpdatedDate}}</td>
                <td>{{data.Blog_Author}}</td>
                <td>{{data.Blog_PublishedStatus}}</td>
                {% comment %} <td><a target="_blank" class="btn btn-primary rounded-3" href="#" onclick="renderPathForBlogCategoryFunction('blog','{{ data.id }}'); return false;">View Details</a></td> {% endcomment %}
                <td><a class="btn btn-primary rounded-3" href="#" onclick="renderPathForBlogCategoryFunction('edit_blog','{{ data.id }}'); return false;">Edit</a></td>
                {% comment %} <td><a class="btn btn-primary rounded-3 confirm-delete" href="{% url 'delete_blog' data.id %}">Delete</a></td> {% endcomment %}
            </tr>
            {% endfor %} 

            </tbody>
        </table>
    </div>
</div>

</section>

<script>
        $(document).ready(function() {
       $('#mytable').dataTable( {
           buttons: [
           'copy', 'csv', 'excel', 'pdf', 'print'
           ],
          "info":           true,
          "paging":         true,

      } );
    } );


</script>



<script>
    $(document).on("click",".confirm-delete",function(){
        return confirm("Are you sure you want to delete this blog..?");
    })

</script>


{% endblock %}

admin_app/templates/admin_app/admin_login.html
{% extends 'admin_app/base.html' %}
{% load static %}
{% load custom_tags %}
{% block admin_login_content %}
  <!-- SCRIPT FOR BAR CHART STARTS -->
  <style>
    .content-body {
      margin-left: unset !important;
    }
  </style>
  <div class="container mt-3 ">
    <!-- Error Block Starts -->
    <div class="row">
      {% if messages %}
        {% for message in messages %}
          <div class="col-lg-12">
            <div class="alert alert-primary">{{ message }}</div>
          </div>
        {% endfor %}
      {% endif %}
    </div>
    <!-- Error Block Ends -->

    <div class="login-form-bg  ">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-xl-6">
            <div class="form-input-content">
              <img class="img-fluid w-50 mx-auto py-3" src="{% static '../../static/admin_app/images/bhashanet-logo.png' %}" alt="Bhashanet Logo">
              <div class="card login-form mb-0">
               
                <div class="card-body pt-5">
                  <a class="text-center" href="index.html"><h4>Admin Login</h4></a>

                  <form class="mt-5 mb-5 login-input" method="POST">
                    {% csrf_token %}
                    <div class="form-group">{{ form.username }}</div>
                    <div class="form-group">{{ form.password }}</div>
                    <button type="submit" class="btn login-form__btn submit w-100">Submit</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

admin_app/templates/admin_app/admin_login_Not_In_Use.html
{% extends 'admin_app/base.html' %}
{% load static %}
{% load custom_tags %}
{% block admin_login_content %}
  <!-- SCRIPT FOR BAR CHART STARTS -->
  <style>
    .content-body {
      margin-left: unset !important;
    }
  </style>
  <div class="container mt-3 ">
    <!-- Error Block Starts -->
    <div class="row">
      {% if messages %}
        {% for message in messages %}
          <div class="col-lg-12">
            <div class="alert alert-primary">{{ message }}</div>
          </div>
        {% endfor %}
      {% endif %}
    </div>
    <!-- Error Block Ends -->

    <div class="login-form-bg  ">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-xl-6">
            <div class="form-input-content">
              <img class="img-fluid w-50 mx-auto py-3" src="{% static '../../static/admin_app/images/bhashanet-logo.png' %}" alt="Bhashanet Logo">
              <div class="card login-form mb-0">
               
                <div class="card-body pt-5">
                  <a class="text-center" href="index.html"><h4>Admin Login</h4></a>

                  <form class="mt-5 mb-5 login-input" method="POST">
                    {% csrf_token %}
                    <div class="form-group">{{ form.username }}</div>
                    <div class="form-group">{{ form.password }}</div>
                    <button type="submit" class="btn login-form__btn submit w-100">Submit</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

admin_app/templates/admin_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />

    <!-- theme meta -->
    <meta name="theme-name" content="quixlab" />

    <title>Bhashanet Admin Dashboard</title>

    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="images/favicon.png" />

    <!-- Include jQuery -->
    <script src="{% static 'admin_app/js/jquery.min.js' %}"></script>

    <!-- Pignose Calender -->
    <link href="{% static 'admin_app/plugins/pg-calendar/css/pignose.calendar.min.css' %}" rel="stylesheet" />

    <!-- Chartist -->
    <link rel="stylesheet" href="{% static 'admin_app/plugins/chartist/css/chartist.min.css' %}" />
    <link rel="stylesheet" href="{% static 'admin_app/plugins/chartist-plugin-tooltips/css/chartist-plugin-tooltip.css' %}" />

    <!-- Custom Stylesheet -->
    <link href="{% static 'admin_app/css/style.css' %}" rel="stylesheet" />

    <!-- Dashboard2 Datatable CSS Files -->
    <link href="{% static 'admin_app/css/datatable/dataTables.dataTables.css' %}" rel="stylesheet" />
    <link href="{% static 'admin_app/css/datatable/buttons.dataTables.css' %}" rel="stylesheet" />

    <!-- Dashboard2 Datatable Buttons JS Files -->
    <script src="{% static 'admin_app/js/datatable/dataTables.js' %}"></script>
    <script src="{% static 'admin_app/js/datatable/dataTables.buttons.js' %}"></script>
    <script src="{% static 'admin_app/js/datatable/buttons.dataTables.js' %}"></script>
    <script src="{% static 'admin_app/js/datatable/jszip.min.js' %}"></script>
    <script src="{% static 'admin_app/js/datatable/buttons.html5.min.js' %}"></script>
    <script src="{% static 'admin_app/js/datatable/buttons.print.min.js' %}"></script>

    <!-- Chartjs -->
    <script src="{% static 'admin_app/plugins/chart.js/Chart.bundle.min.js' %}"></script>
  </head>

  <body>
    <!-- ***********Preloader Starts ************* -->
    <div id="preloader">
      <div class="loader">
        <svg class="circular" viewBox="25 25 50 50">
          <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
        </svg>
      </div>
    </div>
    <!-- ***********Preloader Ends ************* -->

    <!-- ***********Main wrapper Starts ************* -->
    <div id="main-wrapper">
      {% include 'admin_app/navbar.html' %}

      {% include 'admin_app/topbar.html' %}

      {% include 'admin_app/sidebar.html' %}

      <!-- ***********Content body starts************* -->
      <div class="content-body">
        {% block home_content %}

        {% endblock %}

        {% block url_add_form_content %}

        {% endblock %}

        {% block total_record_table_content %}

        {% endblock %}

        {% block idn_domain_record_content %}

        {% endblock %}

        {% block idn_domain_forms_content %}

        {% endblock %}

        {% block dashboard_content %}

        {% endblock %}

        {% block email_compose %}

        {% endblock %}

        {% block sent_email_view_content %}

        {% endblock %}

        {% block sent_email_view_detail %}

        {% endblock %}

        {% block edit_idn_domain_forms_content %}

        {% endblock %}

        {% block barchart_content %}

        {% endblock %}

        {% block log_content %}

        {% endblock %}

        {% block upload_excel_file_content %}

        {% endblock %}

        {% block dashboard2_content %}

        {% endblock %}

        {% block admin_login_content %}

        {% endblock %}

        {% block idn_domain_list_content %}

        {% endblock %}

        {% block english_domain_list_content %}

        {% endblock %}


        <!--ADD BLOG STARTS -->
        {% block add_blog %}
        {% endblock %}
        <!---ADD BLOG ENDS -->

        <!--ADD BLOG DATATABLE STARTS -->
        {% block blog_datatable %}
        {% endblock %}
        <!---ADD BLOG DATATABLE ENDS -->

        <!-- user_register STARTS -->
        {% block user_register %}
        {% endblock %}
        <!-- user_register ENDS -->

        <!-- user_login STARTS -->
        {% block user_login %}
        {% endblock %}
        <!-- user_login ENDS -->

        <!-- user_profile STARTS -->
        {% block user_profile %}
        {% endblock %}
        <!-- user_profile ENDS -->

        <!-- change_password STARTS -->
        {% block change_password %}
        {% endblock %}
        <!-- change_password ENDS -->


        {% block otp_form %}
        {% endblock  %}

        <!-- forgot_password_token_page STARTS -->
        {% block forgot_password_token_page %}
        {% endblock %}
        <!-- forgot_password_token_page ENDS -->

        <!-- change_password STARTS -->
        {% block forgot_password %}
        {% endblock %}
        <!-- change_password ENDS -->

        <!-- change_password STARTS -->
        {% block password_creation %}
        {% endblock %}
        <!-- change_password ENDS -->

        <!-- change_password STARTS -->
        {% block success_page %}
        {% endblock %}
        <!-- change_password ENDS -->




        
      </div>
      <!-- ***********Content body end************* -->

      {% include 'admin_app/footer.html' %}
    </div>
    <!-- ***********Main wrapper Ends ************* -->

    {% include 'admin_app/footer_jsfiles.html' %}
  </body>
</html>

admin_app/templates/admin_app/edit_idn_domain_forms.html
{% extends 'admin_app/base.html' %}
{% load static %}
{% block edit_idn_domain_forms_content %}
  <div class="container-fluid mt-3">
    <!-- Error Block Starts -->
    <div class="row">
      {% if messages %}
        {% for message in messages %}
          <div class="col-lg-12">
            <div class="alert alert-primary">{{ message }}</div>
          </div>
        {% endfor %}
      {% endif %}

      {% if idn_dashboard_form_obj.non_field_errors %}
        {% for error in idn_dashboard_form_obj.non_field_errors %}
          <div class="col-lg-12">
            <div class="alert alert-primary">{{ error|escape }}</div>
          </div>
        {% endfor %}
      {% endif %}
    </div>
    <!-- Error Block Ends -->

    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-body">
            <h4 class="card-title">Add New IDN Domain</h4>
            <div class="basic-form">
              <form method="POST" action="" novalidate>
                {% csrf_token %}
                <div class="form-group">
                  <label>Select English Domain</label>
                  {{ idn_dashboard_form_obj.English_domain }}
                </div>
                <div class="form-group">
                  <label>Select IDN Language</label>
                  {{ idn_dashboard_form_obj.Language }}
                </div>
                <div class="form-group">
                  <label>Enter IDN URL</label>
                  {{ idn_dashboard_form_obj.IDN_domain }}
                </div>
                <div class="form-group">
                  <input type="hidden" name="form_type" value="IDNDOMAINFORM" />
                </div>

                <div class="outline-button">
                  <a class="btn mb-1 btn-outline-primary" href="{% url 'admin_app:dashboard2' %}">Back</a>
                  <button type="submit" class="btn mb-1 btn-outline-primary">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

admin_app/templates/admin_app/footer.html
{% load static %}
<!--        **********************************
            Footer start
        ***********************************        -->
<div class="footer">
  <div class="copyright">
    <p>
      All Copyright &copy; Reserved 2024
    </p>
  </div>
</div>
<!--        **********************************
                Footer end
            ***********************************        -->

admin_app/templates/admin_app/navbar.html
{% load static %}

<!--                          **********************************
            Nav header start
        ***********************************                          -->
{% if request.user.is_authenticated %}
<div class="nav-header">
  <div class="brand-logo">
    <a href="{% url 'admin_app:dashboard2' %}" class="d-flex flex-column align-items-center">
      <b>
        <span class="logo-abbr logo-compact text-black" style="font-size:16px">
          Admin
         </span>
      </b>

      <span class="brand-title">
        <img class="img-fluid w-100 mx-auto" src="{% static 'admin_app/images/bhashanet-logo.png' %}" alt="Your Logo">
      </span>
    </a>
  </div>
</div>

{% endif %}
<!--                          **********************************
                Nav header end
            ***********************************                          -->